asset_path: /home/sirui/Codes/InterMimic/isaacgym/src/intermimic/data/assets/objects/objects/woodchair/woodchair.obj
usd_dir: /home/sirui/Codes/InterMimic/isaaclab/src/intermimic_lab/assets/usd/woodchair
usd_file_name: woodchair_1.000_1.000_1.000
force_usd_conversion: false
make_instanceable: false
mass_props:
  mass: null
  density: 200.0
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: false
  disable_gravity: false
  linear_damping: 0.01
  angular_damping: 0.01
  max_linear_velocity: 1000.0
  max_angular_velocity: 1000.0
  max_depenetration_velocity: 100.0
  max_contact_impulse: null
  enable_gyroscopic_forces: true
  retain_accelerations: null
  solver_position_iteration_count: 4
  solver_velocity_iteration_count: 1
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: null
  contact_offset: 0.02
  rest_offset: 0.02
  torsional_patch_radius: null
  min_torsional_patch_radius: null
mesh_collision_props:
  usd_func: pxr.UsdPhysics:MeshCollisionAPI
  physx_func: pxr.PhysxSchema:PhysxConvexDecompositionCollisionAPI
  mesh_approximation_name: convexDecomposition
  hull_vertex_limit: 64
  max_convex_hulls: 64
  min_thickness: null
  voxel_resolution: 300000
  error_percentage: null
  shrink_wrap: null
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2025-12-18 at 00:44:52.
##
